name: Deployment Workflow
on:
  push:
    branches:
    - master

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: testing portail-dpcb.tech server ssh connection
      uses: appleboy/ssh-action@master
      with:
        host: 51.210.15.73
        username: debian
        key: ${{secrets.PORTAIL_SECRET}}
        port: 22
        script: cd /var/www/portail-dpcb/" && git pull
